-- ============================================================
-- 丰富 contents 表的正文内容（用 Markdown 替换占位文本）
-- 仅 UPDATE content 字段，保留其他字段；可在任意时刻安全重跑
-- ============================================================
USE deployment_learning;

-- build 领域
UPDATE contents SET content = '## 什么是构建\n\n在前端开发中，**构建（Build）** 是把源代码转换成浏览器可部署、可高效加载的静态资源的过程。一个完整的构建流程通常包含：\n\n- 编译：把 TypeScript / JSX / Vue SFC 等转译为浏览器原生支持的 HTML / CSS / JS\n- 打包：把零散的模块合并为少量文件，减少 HTTP 请求\n- 压缩：移除注释、空白，缩短变量名，启用 Gzip / Brotli\n- 资源处理：图片压缩、字体子集化、CSS 雪碧图\n- 哈希命名：根据内容生成文件 hash，用于长期缓存\n\n## 为什么需要构建\n\n现代前端项目动辄几百个文件、几十兆源码。如果不构建，浏览器要发几百个请求；构建后只需 3-5 个文件，加载时间可以从 10 秒级降到 1 秒级。\n\n## 主流工具对比\n\n| 工具 | 定位 | 速度 | 适用场景 |\n|------|------|------|----------|\n| Webpack | 通用打包器 | 中 | 复杂应用、需要细粒度优化 |\n| Vite | 现代 Dev Server + Rollup | 极快 | Vue / React SPA |\n| esbuild | Go 编写的极速打包器 | 极快 | 库、纯 TS 项目 |\n| Parcel | 零配置打包器 | 快 | 小型项目、Demo |\n\n> 提示：对 Vue 3 项目首选 **Vite**，开发体验和构建速度都领先。\n\n## 下一步\n\n建议先掌握 Vite 的基础配置，再学习如何通过 splitChunks、Tree Shaking 等手段优化构建产物。' WHERE id = 1;

UPDATE contents SET content = '## 构建优化的核心目标\n\n构建优化通常围绕三个维度展开：\n\n1. **体积优化**：减少产物大小，加快首屏加载\n2. **缓存优化**：利用浏览器长期缓存，减少重复下载\n3. **加载优化**：按需加载，避免一次性下载整个应用\n\n## 常用手段\n\n### 1. 代码分割（Code Splitting）\n\n把单个巨大的 bundle 拆成多个 chunk，按路由或交互触发加载：\n\n```ts\n// 路由级懒加载\nconst Detail = () => import(\'./Detail.vue\')\n```\n\n### 2. Tree Shaking\n\nES Modules 的静态结构让构建器可以分析哪些导出未被使用，直接删除。前提：\n\n- 使用 `import / export`，不要用 `require`\n- 在 `package.json` 中设置 `"sideEffects": false`\n- 避免整体导入：`import { get } from \'lodash-es\'` ✅，`import _ from \'lodash\'` ❌\n\n### 3. 资源压缩与哈希命名\n\n```ts\n// vite.config.ts\nexport default {\n  build: {\n    rollupOptions: {\n      output: {\n        chunkFileNames: \'assets/[name]-[hash].js\',\n        assetFileNames: \'assets/[name]-[hash].[ext]\'\n      }\n    }\n  }\n}\n```\n\n带 hash 的文件名可以配合强缓存（`Cache-Control: max-age=31536000`），文件不变时浏览器永不重新下载。\n\n### 4. 关键 CSS 内联\n\n把首屏需要的 CSS 直接内联到 HTML，避免阻塞渲染。Lighthouse 中的 FCP / LCP 指标会显著改善。\n\n## 度量\n\n优化前后用 [Lighthouse](https://developer.chrome.com/docs/lighthouse/) 跑一遍，关注：\n- FCP（First Contentful Paint）\n- LCP（Largest Contentful Paint）\n- TBT（Total Blocking Time）\n\n> 优化是个迭代过程，**先量化、再优化、再量化**，避免凭感觉调整。' WHERE id = 2;

-- platform 领域
UPDATE contents SET content = '## Vercel 是什么\n\n[Vercel](https://vercel.com) 是一个面向前端框架的托管平台，由 Next.js 团队维护。它把部署简化到「push 代码 → 自动上线」的程度，是前端开发者的首选平台之一。\n\n## 核心特性\n\n- **Git 触发部署**：连接 GitHub / GitLab，每次 push 自动构建并部署\n- **预览部署**：每个 PR / 分支生成独立的预览 URL，方便分享给同事评审\n- **自动 HTTPS**：所有域名自动签发 Let''s Encrypt 证书，无需手动配置\n- **全球 CDN**：静态资源走边缘节点，动态函数走最近网关\n- **Serverless Functions**：可以直接写 `/api/xxx.ts` 部署为 API\n\n## 部署一个 Vue 项目的步骤\n\n1. 在 Vercel 控制台 **New Project → Import Git Repository**\n2. 选择框架预设（Vite / Vue CLI）\n3. 配置构建命令（默认 `npm run build`）和输出目录（默认 `dist`）\n4. 点击 **Deploy**，等 1-2 分钟即可拿到 `xxx.vercel.app` 域名\n\n## 限制（免费版）\n\n| 项目 | 限制 |\n|------|------|\n| 月度带宽 | 100 GB |\n| Serverless 函数执行时长 | 100 GB-Hours |\n| 构建时长 | 6000 分钟/月 |\n| 团队成员 | 1 人（个人版） |\n\n> 适合个人项目、Demo、小型商业站点；高流量商业项目建议升级 Pro。\n\n## 何时选 Vercel\n\n- 用 Next.js / Nuxt / Vite 等 Modern Stack\n- 需要频繁预览部署\n- 不想运维服务器\n- 流量在 100GB/月 以内' WHERE id = 3;

UPDATE contents SET content = '## Netlify 与 Vercel 的差异\n\nNetlify 是 Vercel 的最直接竞品。两者功能高度重叠，但定位略有不同：\n\n- **Vercel**：紧贴 Next.js，对 SSR / ISR 等渲染模式优化更深\n- **Netlify**：更通用，对静态站、表单、Identity（内置鉴权）支持更好\n\n## netlify.toml 配置\n\n在项目根目录创建 `netlify.toml`，可以版本化部署配置：\n\n```toml\n[build]\n  command = "npm run build"\n  publish = "dist"\n\n[[redirects]]\n  from = "/*"\n  to = "/index.html"\n  status = 200\n\n[[headers]]\n  for = "/assets/*"\n  [headers.values]\n    Cache-Control = "public, max-age=31536000, immutable"\n```\n\n关键配置项：\n- `command`：构建命令\n- `publish`：构建产物目录\n- `redirects`：SPA 路由的 history 模式必须配置 fallback 到 `index.html`\n- `headers`：缓存策略、安全头\n\n## 高级特性\n\n### 表单处理\n\n无需后端，HTML 中加 `data-netlify="true"` 即可自动收集表单提交，后台查看或转发到邮箱 / Webhook。\n\n### Netlify Identity\n\n内置的用户系统，支持注册 / 登录 / 角色管理，对接第三方 OAuth（Google / GitHub 等）。\n\n### Split Testing\n\nA/B 测试：基于 cookie 把流量按比例分流到不同分支部署。\n\n## 何时选 Netlify\n\n- 静态站 / JAMstack 项目\n- 需要表单、Identity 等内置服务\n- 团队对 Next.js 依赖不强' WHERE id = 4;

-- server 领域
UPDATE contents SET content = '## 选服务器的关键维度\n\n购买服务器前，先回答几个问题：\n\n1. **部署什么**：静态站、Node.js 服务、Docker 容器？\n2. **流量多大**：日 PV 100 / 1万 / 100万？\n3. **用户在哪**：国内、海外、全球？\n4. **预算多少**：月度可承受成本？\n\n## 主流方案对比\n\n| 平台 | 类型 | 起步价 | 适用场景 |\n|------|------|--------|----------|\n| 阿里云 ECS | 国内云 VM | ¥99/月 | 国内业务、企业合规 |\n| 腾讯云 CVM | 国内云 VM | ¥99/月 | 同上 |\n| AWS EC2 | 国际云 VM | ~$3.5/月 | 海外业务、企业级 |\n| DigitalOcean | 海外 VPS | $4/月 | 个人项目、性价比高 |\n| Vultr | 海外 VPS | $2.5/月 | 短期实验、按小时计费 |\n| Hetzner | 欧洲物理机 | €4/月 | 性价比极致 |\n\n## 配置选择建议\n\n- **CPU**：1 核够个人博客 / 小流量站；2-4 核适合 Web 应用\n- **内存**：1GB 跑 Linux + Nginx 够用；跑 Node.js / 数据库建议 2GB+\n- **磁盘**：20GB SSD 起步，IO 性能远胜 HDD\n- **带宽**：国内 1-5Mbps 起步，海外通常 1Gbps 共享\n\n## 地域选择\n\n- **国内用户**：买国内云（需 ICP 备案）或香港机房（免备案、延迟稍高）\n- **海外用户**：选目标市场附近的 AWS / DigitalOcean 区域\n- **全球用户**：用 CDN（Cloudflare / Cloudfront）做边缘加速，源站选便宜地域\n\n> 警告：国内服务器必须完成 ICP 备案才能解析域名，备案需 15-20 个工作日。' WHERE id = 5;

UPDATE contents SET content = '## SSH 是什么\n\n**SSH（Secure Shell）** 是 Linux 服务器远程管理的标准协议，所有命令、文件传输都通过加密通道进行。比 FTP / Telnet 安全得多。\n\n## 准备密钥对\n\n本地生成密钥对（公钥 + 私钥）：\n\n```bash\nssh-keygen -t ed25519 -C "your_email@example.com"\n```\n\n- 生成的私钥：`~/.ssh/id_ed25519`（**绝对不能泄露**）\n- 生成的公钥：`~/.ssh/id_ed25519.pub`（可放心上传到服务器）\n\n> 推荐使用 `ed25519` 算法，比 RSA 更短更快更安全。\n\n## 上传公钥到服务器\n\n首次用密码登录后，把公钥追加到服务器的 `~/.ssh/authorized_keys`：\n\n```bash\nssh-copy-id -i ~/.ssh/id_ed25519.pub user@server_ip\n```\n\n之后无需密码即可登录。\n\n## 基础连接命令\n\n```bash\n# 标准登录\nssh -i ~/.ssh/id_ed25519 user@server_ip\n\n# 指定端口\nssh -p 2222 user@server_ip\n\n# 端口转发（把本地 8080 转到服务器 80）\nssh -L 8080:localhost:80 user@server_ip\n```\n\n## 安全加固清单\n\n1. **禁用密码登录**：编辑 `/etc/ssh/sshd_config`，设 `PasswordAuthentication no`\n2. **禁用 root 登录**：设 `PermitRootLogin no`，用普通用户 + sudo\n3. **改默认端口**：把 22 改为其他端口，减少自动化扫描\n4. **限制 IP**：安全组 / iptables 限制来源 IP\n5. **使用 fail2ban**：自动封禁暴力破解 IP\n\n## 常见问题\n\n- **Permission denied (publickey)**：检查公钥权限、`authorized_keys` 是否 600、私钥是否被 ssh-agent 加载\n- **Connection refused**：服务器 sshd 未启动或端口被防火墙拦截\n- **Host key verification failed**：服务器重装后 host key 变化，删除 `~/.ssh/known_hosts` 中对应行' WHERE id = 6;

-- automation 领域
UPDATE contents SET content = '## GitHub Actions 是什么\n\n**GitHub Actions** 是 GitHub 内置的 CI/CD 服务，把构建、测试、部署等任务直接挂在仓库里，push 代码或开 PR 时自动触发。\n\n## 核心概念\n\n- **Workflow**：一个 YAML 文件，定义在 `.github/workflows/` 目录下\n- **Job**：工作流中的一组步骤，运行在同一个 runner 上\n- **Step**：具体动作，可以是 shell 命令或预制的 Action\n- **Action**：可复用的步骤单元，比如 `actions/checkout@v4`\n\n## Hello World 示例\n\n`.github/workflows/ci.yml`：\n\n```yaml\nname: CI\n\non:\n  push:\n    branches: [main]\n  pull_request:\n    branches: [main]\n\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 20\n          cache: npm\n      - run: npm ci\n      - run: npm run lint\n      - run: npm run build\n      - run: npm test\n```\n\n## 常用触发器\n\n- `push`：推送时触发\n- `pull_request`：PR 创建/更新时触发\n- `schedule`：定时（cron 语法）\n- `workflow_dispatch`：手动触发\n- `release`：发布 Release 时触发\n\n## 与部署集成\n\n构建完成后，可以直接调用部署脚本或使用市场 Action：\n\n```yaml\n- name: Deploy to Vercel\n  run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}\n```\n\n> 提示：在仓库 Settings → Secrets 中存放 token 等敏感信息，不要写在 YAML 中。' WHERE id = 7;

UPDATE contents SET content = '## 为什么要在 CI 中跑测试\n\n代码合并到主分支前自动跑测试，可以：\n\n- **早发现**：bug 越早发现，修复成本越低\n- **防回归**：新代码不能破坏已有功能\n- **强制规范**：所有人 push 前都必须过测试\n- **历史可追溯**：每次提交的测试结果都留档\n\n## 测试金字塔\n\n```\n        ╱ E2E ╲        少量 · 慢 · 高保真\n       ╱──────╲\n      ╱ 集成测试 ╲     中等\n     ╱────────────╲\n    ╱   单元测试    ╲   多 · 快 · 廉价\n   ╱________________╲\n```\n\nCI 中应**单元测试全跑、集成测试关键路径、E2E 仅核心流程**。\n\n## Jest 基础配置\n\n`jest.config.js`：\n\n```js\nmodule.exports = {\n  preset: \'ts-jest\',\n  testEnvironment: \'node\',\n  testMatch: [\'**/__tests__/**/*.test.ts\'],\n  collectCoverage: true,\n  coverageThreshold: {\n    global: { branches: 70, functions: 80, lines: 80 }\n  }\n};\n```\n\n## GitHub Actions 中跑测试\n\n```yaml\njobs:\n  test:\n    runs-on: ubuntu-latest\n    strategy:\n      matrix:\n        node: [18, 20]\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: ${{ matrix.node }}\n      - run: npm ci\n      - run: npm test -- --coverage\n      - name: Upload coverage\n        uses: codecov/codecov-action@v3\n```\n\n## 常见反模式\n\n- ❌ 测试中调用真实数据库 / 外部 API（用 mock 代替）\n- ❌ 测试之间有依赖（应相互独立）\n- ❌ 一个测试覆盖多个分支（拆开，命名清晰）\n- ❌ 用 `setTimeout` 等待异步（用 async/await 或 expect.async）\n\n> 好的测试应该 **AAA**：Arrange（准备）→ Act（执行）→ Assert（断言）。' WHERE id = 8;

-- domain 领域
UPDATE contents SET content = '## 域名购买流程\n\n1. **选注册商**：Namecheap（性价比）/ Cloudflare（成本价）/ 阿里云（国内备案方便）\n2. **查可用性**：在注册商搜索框输入想要的名称\n3. **选后缀**：`.com` 通用、`.dev` 开发者、`.io` 科技圈、`.cn` 国内\n4. **下单**：注意续费价格（首年优惠常陷阱）\n5. **配置 DNS**：在注册商或第三方 DNS 服务商处配置解析\n\n## DNS 记录类型\n\n| 类型 | 用途 | 示例 |\n|------|------|------|\n| A | 域名 → IPv4 | `@ A 1.2.3.4` |\n| AAAA | 域名 → IPv6 | `@ AAAA 2001:db8::1` |\n| CNAME | 域名 → 域名 | `www CNAME example.com` |\n| MX | 邮件服务器 | `@ MX mail.example.com` |\n| TXT | 任意文本（多用于验证） | `@ TXT "v=spf1 -all"` |\n| NS | 委托 DNS 服务 | `@ NS ns1.cloudflare.com` |\n\n## 解析生效时间\n\n- **TTL（Time To Live）**：DNS 记录的缓存时间，通常 300-3600 秒\n- 修改解析后，全球 DNS 服务器按 TTL 逐步刷新\n- 短 TTL 适合频繁切换，长 TTL 减轻 DNS 服务压力\n\n> 修改 DNS 前先把 TTL 调短到 300s，等 24 小时后再改 IP，可以最大限度减少切换中断。\n\n## 域名解析服务商选择\n\n- **Cloudflare**（推荐）：免费、快、自带 CDN / DDoS 防护\n- **DNSPod**：国内速度好，腾讯云生态\n- **阿里云 DNS**：与阿里云服务深度集成\n- **注册商默认 DNS**：通常够用，但功能有限\n\n## 把域名指向 Vercel\n\n```\n@ A 76.76.21.21\nwww CNAME cname.vercel-dns.com\n```\n然后在 Vercel 项目设置中添加域名，自动签发 HTTPS 证书。' WHERE id = 9;

UPDATE contents SET content = '## 为什么需要 HTTPS\n\nHTTP 明文传输，存在三大风险：\n\n1. **窃听**：WiFi / 运营商可以看到你访问的所有内容\n2. **篡改**：运营商可以注入广告、恶意脚本\n3. **伪装**：DNS 劫持后，访问的可能是钓鱼网站\n\nHTTPS = HTTP + TLS，提供加密、完整性、身份验证三重保障，是现代 Web 的标配。\n\n## 申请免费证书：Let''s Encrypt\n\n[Let''s Encrypt](https://letsencrypt.org) 是免费、自动化的证书颁发机构，证书 90 天有效，到期自动续期。\n\n### 使用 Certbot 自动配置\n\n```bash\n# 安装\nsudo apt install certbot python3-certbot-nginx\n\n# 自动配置 Nginx\nsudo certbot --nginx -d example.com -d www.example.com\n\n# 测试自动续期\nsudo certbot renew --dry-run\n```\n\nCertbot 会自动：\n- 验证域名所有权\n- 申请并安装证书\n- 修改 Nginx 配置启用 HTTPS\n- 添加 systemd timer 定期续期\n\n## 手动申请（用于 Vercel / Netlify 等托管平台）\n\n部分平台（如自定义证书）需要手动提供证书文件。可使用 [acme.sh](https://acme.sh)：\n\n```bash\ncurl https://get.acme.sh | sh\nacme.sh --issue -d example.com --dns --keylength ec-256\nacme.sh --install-cert -d example.com --ecc \\\n  --key-file /path/to/key.pem \\\n  --fullchain-file /path/to/cert.pem\n```\n\n## Nginx 配置示例\n\n```nginx\nserver {\n  listen 443 ssl http2;\n  server_name example.com;\n\n  ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;\n  ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;\n  ssl_protocols TLSv1.2 TLSv1.3;\n  ssl_ciphers HIGH:!aNULL:!MD5;\n}\n\n# HTTP 自动跳转 HTTPS\nserver {\n  listen 80;\n  server_name example.com;\n  return 301 https://$host$request_uri;\n}\n```\n\n## 常见问题\n\n- **证书过期**：忘了续期，Certbot timer 未启动 → `sudo systemctl status certbot.timer`\n- **混合内容**：HTTPS 页面加载 HTTP 资源 → 浏览器拦截，需全部改为 HTTPS\n- **HSTS**：通过响应头强制后续都走 HTTPS，进一步加固' WHERE id = 10;

-- container 领域
UPDATE contents SET content = '## Docker 是什么\n\n**Docker** 是一个把应用及其依赖打包成标准化「容器」的工具。容器是轻量级、可移植、隔离的运行环境，比虚拟机更省资源。\n\n## 核心概念\n\n- **Image（镜像）**：只读模板，包含运行应用所需的一切（代码、依赖、OS 库）\n- **Container（容器）**：镜像的运行实例，可启停、删除\n- **Dockerfile**：描述如何构建镜像的文本文件\n- **Registry（仓库）**：存储和分发镜像，如 Docker Hub、阿里云 ACR\n- **Volume（卷）**：持久化数据，独立于容器生命周期\n\n## 第一个 Dockerfile\n\n一个 Node.js Express 应用的最小 Dockerfile：\n\n```dockerfile\nFROM node:20-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --only=production\nCOPY . .\nEXPOSE 3000\nCMD ["node", "server.js"]\n```\n构建并运行：\n\n```bash\ndocker build -t myapp .\ndocker run -p 3000:3000 myapp\n```\n\n## 镜像分层与缓存\n\nDockerfile 中每条指令生成一层。某层变化会使其后所有层缓存失效。优化技巧：\n\n- 把变动少的指令放前面（如安装依赖）\n- 把变动多的指令放后面（如 COPY 源码）\n- 使用 `.dockerignore` 排除 `node_modules`、`.git` 等\n\n## 常用命令\n\n```bash\ndocker ps              # 查看运行中的容器\ndocker ps -a           # 查看所有容器（含停止）\ndocker images          # 查看本地镜像\ndocker logs <id>       # 查看容器日志\ndocker exec -it <id> sh  # 进入容器交互\ndocker stop <id>       # 停止\ndocker rm <id>         # 删除容器\ndocker rmi <image>     # 删除镜像\n```\n\n## 适用场景\n\n- 同一应用在不同环境（开发/测试/生产）一致性运行\n- 微服务架构中各服务独立部署\n- CI/CD 流水线中的环境隔离\n- 一台主机跑多个项目，互不干扰' WHERE id = 11;

UPDATE contents SET content = '## Docker Compose 是什么\n\n**Docker Compose** 是定义和运行多容器 Docker 应用的工具。用一个 `docker-compose.yml` 描述所有服务、网络、卷，一条命令启停整个应用栈。\n\n## 典型场景：Web + DB\n\n一个 Node.js 应用 + MySQL 数据库的 `docker-compose.yml`：\n\n```yaml\nversion: \'3.9\'\n\nservices:\n  app:\n    build: .\n    ports:\n      - "3000:3000"\n    environment:\n      DB_HOST: db\n      DB_USER: root\n      DB_PASSWORD: secret\n      DB_NAME: myapp\n    depends_on:\n      db:\n        condition: service_healthy\n    restart: unless-stopped\n\n  db:\n    image: mysql:8\n    environment:\n      MYSQL_ROOT_PASSWORD: secret\n      MYSQL_DATABASE: myapp\n    volumes:\n      - db_data:/var/lib/mysql\n    healthcheck:\n      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]\n      interval: 5s\n      timeout: 3s\n      retries: 10\n    restart: unless-stopped\n\nvolumes:\n  db_data:\n```\n\n## 常用命令\n\n```bash\n# 启动所有服务（后台）\ndocker compose up -d\n\n# 查看运行状态\ndocker compose ps\n\n# 查看日志（实时）\ndocker compose logs -f app\n\n# 停止并删除容器（保留卷）\ndocker compose down\n\n# 停止并删除容器 + 卷（清空数据）\ndocker compose down -v\n\n# 重新构建镜像\ndocker compose build\n```\n\n## 核心字段\n\n- `build`：从本地 Dockerfile 构建\n- `image`：直接使用镜像\n- `ports`：端口映射 `宿主:容器`\n- `volumes`：数据持久化\n- `environment` / `env_file`：环境变量\n- `depends_on`：启动顺序（仅控制顺序，不等待 ready；用 `healthcheck` 才能等真正就绪）\n- `restart`：失败后自动重启策略\n- `healthcheck`：健康检查，决定服务是否真正可用\n\n## 多环境管理\n\n通过多个 override 文件实现：\n\n```bash\ndocker compose -f docker-compose.yml -f docker-compose.dev.yml up\ndocker compose -f docker-compose.yml -f docker-compose.prod.yml up -d\n```\n\n> 提示：生产环境务必配置 `restart: unless-stopped` 和 `healthcheck`，保证服务自愈。' WHERE id = 12;
